### PR TITLE
Save computation time with \K

### PR DESCRIPTION
**Pull request by Hywan**

### CODE REVIEW

**Comment by CircleCode** [comment]
doesn't this optimisation prevent user for being able to use it in its pattern ?

**Comment by Hywan** [comment]
Nop.

**Comment by Savageman** [comment]
If I undestand this correctly, \K allows to capture the match later? Could it be used at the end of the pattern to prevent the whole match?
Also you said "save computation time", shouldn't it rather save memory?

**Comment by Hywan** [comment]
From [man page of PCRE](http://pcre.org/pcre.txt):

```
 Resetting the match start

    The  escape sequence \K causes any previously matched characters 
```

not to
        be included in the final matched sequence. For example, the pattern:

```
      foo\Kbar

    matches "foobar", but reports that it has matched "bar". This  
```

feature
        is  similar  to  a lookbehind assertion (described below). 
However, in
        this case, the part of the subject before the real match does 
not  have
        to  be of fixed length, as lookbehind assertions do. The use of 
\K does
        not interfere with the setting of captured  substrings. For  
example,
        when the pattern

```
      (foo)\Kbar

    matches "foobar", the first substring is still set to "foo".

    Perl  documents  that  the  use  of  \K  within assertions is 
```

"not well
        defined". In PCRE, \K is acted upon  when  it  occurs inside  
positive
        assertions, but is ignored in negative assertions.

**Pull request closed without merging**
